"""empty message

Revision ID: 0408cd97bfb2
Revises: 40c29e0a4d24
Create Date: 2019-09-27 00:16:14.919014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0408cd97bfb2'
down_revision = '40c29e0a4d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ingrediente', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingrediente', type_='unique')
    # ### end Alembic commands ###
