"""empty message

Revision ID: 1b63071bc096
Revises: 8fab36ae3f8c
Create Date: 2019-09-21 16:42:48.906095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b63071bc096'
down_revision = '8fab36ae3f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('receta_ibfk_1', 'receta', type_='foreignkey')
    op.drop_column('receta', 'autor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receta', sa.Column('autor', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('receta_ibfk_1', 'receta', 'profile', ['autor'], ['id'])
    # ### end Alembic commands ###
