"""empty message

Revision ID: 398aff8b7981
Revises: c1f9f4c34aef
Create Date: 2019-09-21 22:53:48.369688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '398aff8b7981'
down_revision = 'c1f9f4c34aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingrediente.id'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['receta.id'], ),
    sa.PrimaryKeyConstraint('receta_id', 'ingrediente_id')
    )
    op.drop_table('receta_ingrediente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receta_ingrediente',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_receta', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_ingrediente', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('quantity', mysql.FLOAT(), nullable=False),
    sa.Column('messurment', mysql.ENUM('mililiter', 'miligram', 'ounce'), nullable=False),
    sa.ForeignKeyConstraint(['id_ingrediente'], ['ingrediente.id'], name='receta_ingrediente_ibfk_2'),
    sa.ForeignKeyConstraint(['id_receta'], ['receta.id'], name='receta_ingrediente_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('tags')
    # ### end Alembic commands ###
