"""empty message

Revision ID: 40c29e0a4d24
Revises: 016ce336e883
Create Date: 2019-09-26 23:00:29.133067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c29e0a4d24'
down_revision = '016ce336e883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('id_ingrediente', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock', 'ingrediente', ['id_ingrediente'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.drop_column('stock', 'id_ingrediente')
    # ### end Alembic commands ###
