"""empty message

Revision ID: 539c2faa8462
Revises: 2d8ed7e9e287
Create Date: 2019-09-10 23:17:07.371588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539c2faa8462'
down_revision = '2d8ed7e9e287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('ing_qty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('association', 'ing_qty')
    # ### end Alembic commands ###
