"""empty message

Revision ID: 59e02ccd0c8a
Revises: b63a73aa2f5a
Create Date: 2019-10-03 10:35:28.427516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59e02ccd0c8a'
down_revision = 'b63a73aa2f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receta', 'guia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receta', sa.Column('guia', mysql.VARCHAR(length=200), nullable=False))
    # ### end Alembic commands ###
