"""empty message

Revision ID: 5bf021b25530
Revises: 1d396110930e
Create Date: 2019-09-21 14:27:24.292192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5bf021b25530'
down_revision = '1d396110930e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receta', sa.Column('autor', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'receta', 'profile', ['autor'], ['id'])
    op.drop_constraint('receta_ingrediente_ibfk_1', 'receta_ingrediente', type_='foreignkey')
    op.drop_column('receta_ingrediente', 'autor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receta_ingrediente', sa.Column('autor', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('receta_ingrediente_ibfk_1', 'receta_ingrediente', 'profile', ['autor'], ['id'])
    op.drop_constraint(None, 'receta', type_='foreignkey')
    op.drop_column('receta', 'autor')
    # ### end Alembic commands ###
