"""empty message

Revision ID: 9471465b0962
Revises: 1b63071bc096
Create Date: 2019-09-21 17:38:04.283812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9471465b0962'
down_revision = '1b63071bc096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stock_ibfk_1', 'stock', type_='foreignkey')
    op.drop_column('stock', 'id_ingrediente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('id_ingrediente', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('stock_ibfk_1', 'stock', 'ingrediente', ['id_ingrediente'], ['id'])
    # ### end Alembic commands ###
