"""empty message

Revision ID: b63a73aa2f5a
Revises: d0beda7167c9
Create Date: 2019-10-03 10:33:07.118147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63a73aa2f5a'
down_revision = 'd0beda7167c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receta', sa.Column('guianew', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receta', 'guianew')
    # ### end Alembic commands ###
