"""empty message

Revision ID: b87f9c5096d3
Revises: 9471465b0962
Create Date: 2019-09-21 17:42:37.333101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b87f9c5096d3'
down_revision = '9471465b0962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('price_ibfk_1', 'price', type_='foreignkey')
    op.drop_column('price', 'id_ingrediente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('id_ingrediente', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('price_ibfk_1', 'price', 'ingrediente', ['id_ingrediente'], ['id'])
    # ### end Alembic commands ###
