"""empty message

Revision ID: d0beda7167c9
Revises: adef4f71c31c
Create Date: 2019-10-03 00:04:49.602746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0beda7167c9'
down_revision = 'adef4f71c31c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receta', sa.Column('guia', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receta', 'guia')
    # ### end Alembic commands ###
