"""empty message

Revision ID: dec3c51d8ba1
Revises: 539c2faa8462
Create Date: 2019-09-10 23:52:16.972737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec3c51d8ba1'
down_revision = '539c2faa8462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('stock', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'stock')
    # ### end Alembic commands ###
